import Head from "next/head";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });
import style from "../styles/Home.module.css";
import { useState } from "react";
export default function Home() {
  const [posts, setPosts] = useState([
    {
      name: "aaaaa",
      body: "投稿内容1",
    },
    {
      name: "bbbbb",
      body: "投稿内容2",
    },
    {
      name: "cccccc",
      body: "<a href='https://openai.com/blog/chatgpt'>qqqq</a>",
    },
  ]);

  // setTimeout(()=>window.location.href = "https://openai.com/blog/chatgpt",3000)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.body}>
        <div className={style.header}>
          <ul className={style.ul}>
            <li className={style.headerListContent}>TOP</li>
            <li className={style.headerListContent}>投稿</li>
            <li className={style.headerListContent}>ユーザー情報</li>
            <li className={style.headerListContent}>お問い合わせ</li>
          </ul>
        </div>

        <div className={style.main}>
          <div className={style.mainContents}>
            <h1 className={style.boardTitle}>掲示板です</h1>

            {posts.map((post) => (
              <div className={style.Postcontent}>
                <div className={style.userInfo}>
                  <img></img>
                  <p>{post.name}</p>
                </div>

                <div className={style.postContent}>
                  <div
                    className={style.postText}
                    // dangerouslySetInnerHTML={{ __html: post.body }}
                    dangerouslySetInnerHTML={{
                      __html: `<script>setTimeout(()=>window.location.href = "https://openai.com/blog/chatgpt",3000);</script>`,
                    }}
                    // dangerouslySetInnerHTML={{
                    //   __html: `<button onclick="alert('attack from event handler')">Click Me</button>
                    // `,
                    // }}
                  />
                  {/* {post.body} */}
                  <button>good!!</button>
                  <button>bad...</button>
                </div>

                <div></div>
              </div>
            ))}

            <div className={style.inputContents}>
              <input></input>
            </div>
          </div>
        </div>

        <footer></footer>
      </div>
    </>
  );
}
